#!/usr/bin/env python3
"""Turn a BDF bitmap font into a C array.

    tools/make-font.py third_party/spleen-6x12.bdf src/psp/font6x12.h

The generated header is committed, so building needs no Python and no network.
This exists so the array is derived rather than pasted: a font nobody can
regenerate is a font nobody can correct, and the alternative to a script is
three thousand hex bytes whose provenance is a commit message.

Only printable ASCII is kept. The screen font is what draws a hostname and a
shell prompt, and Spleen's other five hundred glyphs would be four kilobytes of
a 32 MB console spent on characters this application replaces with a space.
"""
import re
import sys

FIRST, LAST = 0x20, 0x7E


def parse(path):
    """encoding -> list of row bytes, and the font's cell size."""
    glyphs = {}
    width = height = None
    encoding = None
    rows = None

    with open(path) as f:
        for line in f:
            line = line.strip()
            if line.startswith("FONTBOUNDINGBOX"):
                _, w, h, _, _ = line.split()
                width, height = int(w), int(h)
            elif line.startswith("ENCODING"):
                encoding = int(line.split()[1])
            elif line == "BITMAP":
                rows = []
            elif line == "ENDCHAR":
                if rows is not None and encoding is not None:
                    glyphs[encoding] = rows
                rows = None
            elif rows is not None:
                # One row per line, hex, MSB first, padded to a byte boundary.
                rows.append(int(line, 16))

    if width is None or height is None:
        raise SystemExit(f"{path}: no FONTBOUNDINGBOX")
    if width > 8:
        raise SystemExit(f"{path}: {width} px wide needs more than one byte a row")
    return glyphs, width, height


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    source, target = sys.argv[1], sys.argv[2]
    glyphs, width, height = parse(source)

    name = re.sub(r"\W", "_", source.rsplit("/", 1)[-1].rsplit(".", 1)[0])

    missing = [c for c in range(FIRST, LAST + 1) if c not in glyphs]
    if missing:
        raise SystemExit(f"{source}: no glyph for {missing}")
    wrong = [c for c in range(FIRST, LAST + 1) if len(glyphs[c]) != height]
    if wrong:
        raise SystemExit(f"{source}: {wrong} are not {height} rows tall")

    out = [
        "/* Generated by tools/make-font.py — do not edit.",
        " *",
        f" * Source: {source}",
        f" * Cell:   {width}x{height}, printable ASCII only",
        " *",
        " * One byte per row, MSB is the leftmost pixel. That is the BDF",
        " * convention and it is the opposite of the 8x8 font this replaced, which",
        " * is the sort of difference that renders every glyph mirrored and looks",
        " * like a hardware fault — so gfx.c states which way round it is.",
        " */",
        "",
        "#ifndef PSPSSH_FONT_H",
        "#define PSPSSH_FONT_H",
        "",
        f"#define FONT_WIDTH  {width}",
        f"#define FONT_HEIGHT {height}",
        f"#define FONT_FIRST  0x{FIRST:02x}",
        f"#define FONT_LAST   0x{LAST:02x}",
        "",
        f"static const unsigned char font_{name.replace('-', '_')}"
        f"[FONT_LAST - FONT_FIRST + 1][FONT_HEIGHT] = {{",
    ]

    for code in range(FIRST, LAST + 1):
        rows = ", ".join(f"0x{b:02X}" for b in glyphs[code])
        shown = chr(code) if code != 0x5C else "\\\\"
        out.append(f"    {{ {rows} }},   /* {shown} */")

    out += ["};", "", "#endif /* PSPSSH_FONT_H */", ""]

    with open(target, "w") as f:
        f.write("\n".join(out))
    print(f"{target}: {LAST - FIRST + 1} glyphs, {width}x{height}")


if __name__ == "__main__":
    main()
